### ISSUE TITLE
NUnit tests with TestCaseSource are skipped

### ISSUE THREAD

**Issue by ovatsus** [LambdaFactory/Neptune-public#15]
I was trying this out in FSharp.Data, and I selected all the tests in FSharp.Data.Tests.Http to run, however the two with TestCaseSource attributes were skipped:

![image](https://user-images.githubusercontent.com/738761/38205626-263cb49c-369f-11e8-90ce-350d03fa22d7.png)

My expectation would be that they would still be run, and the sub test cases would show as children nodes in the tree. VS test explorer for comparison:

![image](https://user-images.githubusercontent.com/738761/38205709-7404a838-369f-11e8-81ff-0ccc611da212.png)

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `1.1.0`

**Comment by ovatsus** [comment]
Still doesn't work for me on 1.1.1:

![image](https://user-images.githubusercontent.com/738761/38622707-b30bc4a0-3d9b-11e8-9d18-5183e5981126.png)

**Comment by Krzysztof-Cieslak** [comment]
Yes, I can reproduce it with `Run Project` and `Run File` while it works fine on `Run List`, `Run All` and `Run Test`. Could you check if that’s also the case for you?

**Comment by ovatsus** [comment]
I tried running from the Http.fs node (Run Files), from the FSharp.Data.Test.Http node (Run Tests) and from the specific test node (Run Test), and also on the Run Test line lens on the editor. None of them worked

From the FSharp.Data.Tests.fsproj node (Run Project), I got this error:

![image](https://user-images.githubusercontent.com/738761/38629701-ac1a6744-3dac-11e8-9683-a681afcf527d.png)

**Comment by Krzysztof-Cieslak** [comment]
Could you try `1.1.3` ?

![capture](https://user-images.githubusercontent.com/5427083/38768828-b4653222-3ff9-11e8-9a3a-9de56719cada.PNG)

**Comment by ovatsus** [comment]
Now it works, though other editors usually show the test cases in the hierarchy even before you run the tests, while Neptune only shows after you run them

**Comment by Krzysztof-Cieslak** [comment]
Yes, I do realize that. Unfortunately, that's the disadvantage of the way we detect tests - we're using AST parsing to do that. Thanks to it we get super fast detection, and tests are updated while you edit file (in VS users need to rebuild project to refresh tree view) but this mean we can't detect test cases that are generated on runtime.

**Comment by ovatsus** [comment]
But you could probably still detect that it has a TestCaseSource attribute, right? What about you add a dummy "..." child node in that case, so at least on the tree we can see there are multiple sub cases?
