### ISSUE TITLE
ENOENT on fsproj.neptune.targets

### ISSUE THREAD

**Issue by priort** [LambdaFactory/Neptune-public#20]
I created a new .NET Core xunit project
with ```dotnet new xunit -lang f# -o Tests```
cd into Tests and ran
```dotnet restore```
```dotnet build```

then I reloaded the window in vscode.
I get below error when I click on Run to run the sample test from the xunit template.
```
module Tests

open System
open Xunit

[<Fact>]
let ``My test`` () =
    Assert.True(true)
```

<img width="470" alt="screen shot 2018-06-26 at 16 08 50" src="https://user-images.githubusercontent.com/13556648/41921700-5a4b9a2e-795b-11e8-9749-eec861a4c517.png">

If I insert the Tests.fsproj.neptune.targets into the obj directory, I can run the test and then that file gets deleted.

**Comment by priort** [comment]
This is with latest Neptune 1.3.1 and dotnet --version 2.1.300 on macOS

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `1.3.2`

**Comment by priort** [comment]
Thanks but I updated to 1.3.2 but still get the same error. I tried deleting bin and obj directories and did 
```dotnet clean```
```dotnet restore```
```dotnet build```
and reloaded vscode window

**Comment by Krzysztof-Cieslak** [comment]
Can you please try `1.3.3`

**Comment by priort** [comment]
Works perfect now - thanks a million Kris!
